spring.application.name=comentario-service
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_comentario_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Conexiones externas 
servicios.huesped.url=http://localhost:8082
servicios.hotel.url=http://localhost:8083