server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        # 1. Autorización
        - id: ms-auth-route
          uri: http://autorizacion-service:8081
          predicates:
            - Path=/api/auth/**

        # 2. Huésped
        - id: ms-huespedes-route
          uri: http://huesped-service:8082
          predicates:
            - Path=/api/huespedes/**

        # 3. Hotel
        - id: ms-hoteles-route
          uri: http://hotel-service:8083
          predicates:
            - Path=/api/hoteles/**

        # 4. Habitación
        - id: ms-habitacion-route
          uri: http://habitacion-service:8084
          predicates:
            - Path=/api/habitacion/**

        # 5. Disponibilidad
        - id: ms-disponibilidad-route
          uri: http://disponibilidad-service:8085
          predicates:
            - Path=/api/disponibilidad/**

        # 6. Tarifa
        - id: ms-tarifa-route
          uri: http://tarifa-service:8086
          predicates:
            - Path=/api/tarifa/**

        # 7. Reserva
        - id: ms-reservas-route
          uri: http://reserva-service:8087
          predicates:
            - Path=/api/reservas/**

        # 8. Servicio Extra
        - id: ms-servicios-extras-route
          uri: http://servicioextra-service:8088
          predicates:
            - Path=/api/servicios-extras/**

        # 9. Pago
        - id: ms-pagos-route
          uri: http://pago-service:8089
          predicates:
            - Path=/api/pagos/**

        # 10. Comentario
        - id: ms-comentario-route
          uri: http://comentario-service:8090
          predicates:
            - Path=/api/comentario/**