spring.application.name=reserva

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/sgrh_reserva_db
spring.datasource.username=root
spring.datasource.password=

# Flyway / JPA / Server
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
server.port=8081

# Logging
logging.level.cl.duocuc=DEBUG
logging.file.name=logs/reserva-service.log

# URLs de los microservicios a los que se conectará Reserva
servicios.autorizacion.url=http://localhost:8081
servicios.hotel.url=http://localhost:8082