spring.application.name=reserva-service
server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_reserva_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Conexiones externas 
servicios.autorizacion.url=http://localhost:8081
servicios.huesped.url=http://localhost:8082
servicios.hotel.url=http://localhost:8083