spring.application.name=reserva-service
server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_reserva_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URLs de conexiones externas para tus RestClient
servicios.huesped.url=http://localhost:8082
servicios.habitacion.url=http://localhost:8084
servicios.disponibilidad.url=http://localhost:8085