spring.application.name=servicioextra-service
server.port=8088

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_servicioextra_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL de conexión externa
servicios.reserva.url=http://localhost:8087