spring.application.name=habitacion-service
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_habitacion_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Conexiones externas para RestClient
servicios.hotel.url=http://localhost:8083
