spring.application.name=autorizacion-service
server.port=8081

# Configuración de tu Base de Datos (Ajusta el nombre de la BD si es necesario)
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_autorizacion_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true